<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>$(NoWarn);SKEXP0001;CS0618</NoWarn>
	  <UserSecretsId>f1a4de55-aa98-4312-8214-bb326c4541a2</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />

		<PackageReference Include="Microsoft.SemanticKernel" Version="1.74.0" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.74.0" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Socios.Application\Socios.Application.csproj" />
		<ProjectReference Include="..\Socios.Infrastructure\Socios.Infrastructure.csproj" />
	</ItemGroup>

</Project>